services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    develop:
      watch:
        - path: ./frontend/src
          target: /usr/share/nginx/html/
          action: sync+restart
  db:
   image: postgres:16
   environment:
    POSTGRES_DB: bookstoreDb
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin123
   ports:
    - "5432:5432"
   volumes:
     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./db/data:/var/lib/postgresql/data