services:
  # Docker-compose for each of the 3-tier services: Frontend, db, and backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    develop:
      watch:
        - path: ./frontend/src
          target: /usr/share/nginx/html/
          action: rebuild
  db:
    image: postgres:16
    #TODO Set environment variables for user/pass
    environment:
      POSTGRES_DB: bookstoreDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: "postgresql://admin:admin123@localhost:5432/bookstoreDb"
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./backend/src
          action: rebuild
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend/tsconfig.json
          action: rebuild
