services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: ./frontend/src
          target: /usr/share/nginx/html/
          action: sync+restart
    ports:
      - "80:80"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookstoreDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data