services:
  database:
    image: postgres:12
    environment:
      POSTGRES_DB: bookstoreDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data