ARG NODE_VERSION=20.16.0

FROM node:${NODE_VERSION}-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install

COPY tsconfig.json ./
COPY ./src ./src

RUN npm run build
CMD npm run prod